### PR TITLE
Norms

### PR DESCRIPTION
**Pull request by snunez1**
Add norms and refactor unary-operations.

### CODE REVIEW

**Comment by beberman** [comment]
I've committed the required changes to get triangular-matrix and its tests to work correctly. The code here depends on the lisp-stat version of array-operations so that also should get pushed to quicklisp. The change to zeros is a breaking change so that should go in the notes.

**Review by beberman — COMMENTED** [review]
I've reviewed the changes and run the tests. All changes look good. The zeros change is a significant change because it breaks code on quick-lisp.  Might consider keeping zero-vector

**Comment by snunez1** [comment]
> I've reviewed the changes and run the tests. All changes look good. The zeros change is a significant change because it breaks code on quick-lisp. Might consider keeping zero-vector

What do you mean 'breaks code on quicklisp'?  As far as I can tell, those functions were specific to the linear-algebra system.

**Comment by beberman** [comment]
Well I had a version of array-operations on my machine installed from quicklisp. In that version zeros was defined as taking 1 and only 1 argument - namely the number of zeros to make.  In the new version it takes an optional argument for the numerical type. I had to uninstall the quicklisp version and pull the version from lisp-stat master to make that part of the code function.  Perhaps there is an older version floating out there. I use roswell for package management.

**Pull request merged**
